import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { NextPage } from 'next'
import { useRouter } from 'next/router'
import { Button, ButtonGroup } from "@chakra-ui/react"
import Api from "../api.js"
import { PropsIndexData,BranchItemData } from "../_types/BranchProps"
import BranchCard from '../components/BranchCard'

const Home: NextPage<PropsIndexData> = ({list}) => {
  const router = useRouter()
  const addBranch = (e:any) => {
    e.preventDefault()
    router.push("/branch/add")
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>FatBellies Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to FatBellies
        </h1>

        <p className={styles.description}>
            Manage and Schedule Buffet meal
        </p>

        <Button colorScheme="blue" onClick={addBranch}>Add New Branch</Button>

        <div className={styles.grid}>
          {list.map((item:BranchItemData)=><BranchCard key={item.id} data={item} />)}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/agilworld/resto-app-nextjs-sequelize"
          target="_blank"
          rel="noopener noreferrer"
        >
          Coded by{' '}@agilworld
        </a>
      </footer>
    </div>
  )
}

Home.getInitialProps = async ({req}) => {
  const res:any = await Api.singleRequest(Api.getBranch({page:0,limit:10},null))

  const data = res.data.data
  return { list: data }
}

export default Home

